output_file_name: ''
path_to_output_folder: ''
suffix_file_name: "output"

min_gap_length: 0
max_gap_length: 150

min_flanks_length: 700
max_flanks_length: 10000000

mfe_threshold_hpt: -15
mfe_threshold_hpa: -7

hairpin_similarity_thres: 0.9 # the lower it gets, the more hairpins will be dropped

border_shift: 75 # distance to the right and to the left from gap to look for hairpins

bar_format: "{desc:<50.100} {percentage:3.0f}% |{bar:100}{r_bar}" # progress bar format

num_processes: null # if not specified takes all available cpus

verbosity: 1

avoid_plotting: null