output_file_name: ''
path_to_output_folder: ''
suffix_file_name: "output"

overlap_size: 1000

min_gap_length: 0
max_gap_length: 150

min_flanks_length: 700
max_flanks_length: 10000000

mfe_threshold_hpt: -15
mfe_threshold_hpa: -7

bar_format: "{desc:<50.100} {percentage:3.0f}% |{bar:100}{r_bar}" # progress bar format

num_processes: null # if not specified takes all available cpus

verbosity: 1

avoid_plotting: null